_target_: model.MLP
initial_out_features: 2
sizes: [1024, 400]
layers: ["RBF", "RBF"]
head_type: RBF
num_kernels: 5
radial_function: 
  _target_: model.layer.rbf.rbf_bump
  _partial_: true
norm_function: 
  _target_: model.layer.rbf.l_norm
  _partial_: true