_target_: model.BigModel
pretrained_backbone_name: "resnet18"
pretrained: true
frozen: true
reduced_dim: 256
head:
  _target_: model.MLP
  initial_out_features: 20
  sizes: [256, 1024, 400]
  layers: ["Normal", "Normal"]
  head_type: Normal
  activation: 
    _target_: torch.nn.ReLU