_target_: model.BigModel
pretrained_backbone_name: "resnet18"
pretrained: true
frozen: true
reduced_dim: 256
head:
  _target_: model.MLP
  initial_out_features: 2
  sizes: [256, 100, 10]
  layers: ["Normal", "Normal"]
  head_type: SingleRBFHead