_target_: model.BigModel
pretrained_backbone_name: "resnet18"
head:
  _target_: model.MLP
  initial_out_features: 20
  sizes: [25088, 12000, 4000, 200]
  layers: ["Normal", "Normal", "Normal"]
  head_type: Normal
  activation: 
    _target_: torch.nn.ReLU