_target_: model.BigModel
pretrained_backbone_name: "resnet18"
pretrained: true
frozen: false
head:
  _target_: model.MLP
  initial_out_features: 20
  sizes: [512, 100]
  layers: ["Normal"]
  head_type: Normal
  activation: 
    _target_: torch.nn.ReLU