_target_: model.BigModel
pretrained_backbone_name: "resnet18"
pretrained: true
frozen: true
reduced_dim: 64
head:
  _target_: model.MLP
initial_out_features: 2
sizes: [1024, 100, 10]
layers: ["Normal", "Normal"]
head_type: SingleRBFHead