_target_: model.ResNet18Interval
initial_out_features: 2
pretrained: true
frozen: false
interval_layer_kwargs:
  lower_percentile: 0.05
  upper_percentile: 0.95
  bound_multiplier: 
    _target_: src.model.layer.interval_activation.no_bound
head_type: Normal
head_kwargs: {}
