_partial_: True
_target_: method.Composer
criterion: CrossEntropyLoss
lr: 0.001      
ema_scale: 0.95
beta: 0.1
use_dynamic_alpha: False
criterion_scale: 1.0
reset_rbf_mask: True
plugins:
  - _target_: method.SI
    alpha: 8000.0  
    head_opt: True