_partial_: True
_target_: method.Composer
criterion: MahalanobisDistanceLoss
first_lr: 0.001
lr: 0.001
plugins:
  - _target_: method.RBFNeuronOutReg
    alpha: 0.4
  - _target_: method.Sharpening
    alpha: 0.4
    gamma: 0.1
    K: 64