_partial_: True
_target_: method.Composer
criterion: CrossEntropyLoss
first_lr: 0.001
min_lambda: 1e-8
max_lambda: 1.0
beta: 10.0
lr: 0.001
criterion_scale: 1.0
reset_rbf_mask: False
plugins:
  - _target_: method.EWC
    alpha: 10000
    head_opt: True