_partial_: True
_target_: method.Composer
criterion: CrossEntropyLoss
first_lr: 0.001
lr: 0.001
criterion_scale: 1e-5W
reset_rbf_mask: False
min_lambda: 1e-8
max_lambda: 1.0
beta: 10.0
ema_scale: 0.9
angle_constraint_scale: 2.0
use_dynamic_alpha: True
use_entropy_scale: True
plugins:
  - _target_: method.SI
    alpha: 2048
    head_opt: True