_partial_: True
_target_: method.Composer
criterion: CrossEntropyLoss
first_lr: 0.01  
lr: 0.01     
ema_scale: 0.95
beta: 0.1
use_dynamic_alpha: False
criterion_scale: 1.0
retaingraph: True
plugins:
  - _target_: method.interval_penalization.IntervalPenalization
    var_scale: 0.01
    output_reg_scale: 10000000000.0
    interval_drift_reg_scale: 10000000000.0
    min_var: True
    regularize_past_classifier_outputs: False # If True, only regularizes outputs of old classes. If False, regularizes all outputs.
    regularize_classifier: False