_partial_: True
_target_: method.Composer
criterion: CrossEntropyLoss
first_lr: 0.001  
lr: 0.001      
ema_scale: 0.95
use_dynamic_alpha: True
beta: 0.1
criterion_scale: 1.0
plugins:
  - _target_: method.EWC
    alpha: 8000.0  
    head_opt: True