_partial_: True
_target_: method.Composer
criterion: CrossEntropyLoss
first_lr: 0.001  
lr: 0.001      
min_lambda: 1e-8
max_lambda: 1.0
beta: 2.0  
ema_scale: 0.9
grad_ema_scale_ce: 0.9
use_dynamic_alpha: True
grad_ema_scale_reg: 0.95
huber_delta_scale: 1.5
criterion_scale: 1.0
plugins:
  - _target_: method.EWC
    alpha: 100.0  
    head_opt: True