_partial_: True
_target_: method.Composer
criterion: CrossEntropyLoss
lr: 0.01     
ema_scale: 0.95
beta: 0.1
use_dynamic_alpha: False
criterion_scale: 1.0
retaingraph: True
plugins:
  - _target_: method.interval_penalization_resnet18.ResNet18IntervalPenalization
    var_scale: 0.01
    output_reg_scale: 10000000000.0
    interval_drift_reg_scale: 10000000000.0
    use_hypercube_dist_loss: True
    dil_mode: False
    regularize_classifier: True