_partial_: True
_target_: method.Composer
criterion: CrossEntropyLoss
first_lr: 0.001  
lr: 0.001      
ema_scale: 0.95
beta: 0.1
use_dynamic_alpha: False
criterion_scale: 1.0
plugins:
  - _target_: method.MAS
    alpha: 8000.0  
    head_opt: True