_partial_: True
_target_: method.Composer
criterion: CrossEntropyLoss
first_lr: 0.001  
lr: 0.001      
min_lambda: 1e-8
ema_scale: 0.9
use_dynamic_alpha: True
grad_ema_scale_ct: 0.9
beta: 0.1
criterion_scale: 1.0
plugins:
  - _target_: method.EWC
    alpha: 10000.0  
    head_opt: True