_partial_: True
_target_: method.Composer
criterion: MahalanobisDistanceLoss
first_lr: 0.01
lr: 0.01
criterion_scale: 1e-5
reset_rbf_mask: False
plugins:
  - _target_: method.RBFNeuronOutReg
    alpha: 0.9999999999999999999999
    hidden_layers_reg: False
  - _target_: method.PenultimateLayerReg
    alpha: 0.01