defaults:
  - _self_
  - dataset: cifar100
  - scenario: class_inc
  - model: resnet50
  - method: composer_ewc

exp:
  run_func:
    _target_: experiment.experiment
  seed: 1
  log_dir: # set during runtime to automatically created dir
  batch_size: 512
  epochs: 1
  gen_cm: False
  log_per_batch: False
  detect_anomaly: False
  cleanup: True

fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1
  accelerator: cpu # or gpu

wandb:
  entity: ${oc.env:WANDB_ENTITY}
  project: ${oc.env:WANDB_PROJECT}