defaults:
  - _self_
  - dataset: gauss_regression
  - scenario: regression
  - model: mlp_regression
  - method: composer_interval_penalization_regression

exp:
  run_func:
    _target_: visualization.visualize_regression
  seed: 42
  log_dir: # set during runtime to automatically created dir
  batch_size: 64
  epochs: 500  # More epochs for better convergence
  gen_cm: False
  log_per_batch: False
  detect_anomaly: False
  cleanup: False  # Keep outputs for visualization
  calc_bwt: False
  calc_fwt: False
  acc_table: False
  dil: False

fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1
  accelerator: cpu # or gpu

wandb:
  entity: ${oc.env:WANDB_ENTITY}
  project: ${oc.env:WANDB_PROJECT}
