defaults:
  - dataset: split_mnist
  - scenario: class_inc
  - model: mlp
  - mehod: lwf

_target_: experiment
exp:
  seed: 42
  log_dir: # set during runtime to automatically created dir
  batch_size: 64
  epochs: 5

fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1
  accelerator: cpu # or gpu

wandb:
  entity: ${oc.env:WANDB_ENTITY}
  project: ${oc.env:WANDB_PROJECT}