from .composer import Composer
from .lwf import LwF
from .ewc import EWC
from .mas import MAS
from .si import SI
from .sharpening import Sharpening
from .dreaming import Dreaming
from .dynamic_loss_scaling import DynamicScaling
from .interval_penalization import IntervalPenalization