from .composer import Composer
from .lwf import LwF
from .ewc import EWC
from .mas import MAS
from .si import SI
from .sharpening import Sharpening
from .reg_rbf_neuron_outputs import RBFNeuronOutReg
from .penultimate_layer_reg import PenultimateLayerReg
from .dreaming import Dreaming